---
TheSchemaIs/Presence:
  Enabled: true
  Description: "Check presence of the_schema_is statement in ActiveRecord models"
  Schema: db/schema.rb
  BaseClass: ['ActiveRecord::Base', 'ApplicationRecord']

TheSchemaIs/MissingColumn:
  Enabled: true
  Description: "Check columns missing in the_schema_is definition (but present in schema.rb)"
  Schema: db/schema.rb
  BaseClass: ['ActiveRecord::Base', 'ApplicationRecord']

TheSchemaIs/UnknownColumn:
  Enabled: true
  Description: "Check unknown column in the_schema_is definition (not defined in schema.rb)"
  Schema: db/schema.rb
  BaseClass: ['ActiveRecord::Base', 'ApplicationRecord']

TheSchemaIs/WrongColumnDefinition:
  Enabled: true
  Description: "Check column definition in the_schema_is statement against schema.rb"
  Schema: db/schema.rb
  BaseClass: ['ActiveRecord::Base', 'ApplicationRecord']
